In [ ]:
import pandas as pd
import numpy as np

In [14]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from vaderSentiment) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests->vaderSentiment) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests->vaderSentiment) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests->vaderSentiment) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests->vaderSentiment) (2025.4.26)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [22]:
from scipy.stats import zscore
df = pd.read_excel("Data_Train.xlsx")
df['Title len']=df['Title'].str.len()
df['Reviews'] = df['Reviews'].str.extract(r'(\d+)')
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')
df['Ratings'] = df['Ratings'].str.extract(r'(\d+)')
df['Ratings'] = pd.to_numeric(df['Ratings'], errors='coerce')
df['Reviews'] = zscore(df['Reviews'])
df['Ratings'] = zscore(df['Ratings'])
df['Rating Review score']=df['Ratings'] * df['Reviews']
df['Title Char length']=df['Title'].str.len()
df['Synopsis len']=df['Synopsis'].str.len()
df['Author freq'] = df['Author'].map(df['Author'].value_counts())

In [23]:
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer


# Initialize VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Function to get polarity
def get_sentiment(text):
    score = analyzer.polarity_scores(text)
    return score['compound']  # Compound score gives overall sentiment [-1, 1]

# Apply to column
sentiment_score = df['Synopsis'].apply(get_sentiment)

# Optional: Classify into Positive, Negative, Neutral
def classify_sentiment(score):
    if score >= 0.05:
        return 1
    elif score <= -0.05:
        return -1
    else:
        return 0

df['Synopsis Polarity'] = sentiment_score.apply(classify_sentiment)

In [24]:
df.head(20)

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price,Title len,Rating Review score,Title Char length,Synopsis len,Author freq,Synopsis Polarity
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",0.050347,-0.259449,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00,35,-0.013062,35,791,4,1
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",-1.269032,-0.188133,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93,34,0.238747,34,1146,1,1
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",0.050347,-0.283221,"""During the time men live without a common Pow...",International Relations,Humour,299.00,28,-0.014259,28,1662,3,1
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",0.050347,-0.200019,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00,34,-0.010070,34,426,69,-1
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",1.369725,-0.342651,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62,42,-0.469338,42,659,1,1
5,ChiRunning: A Revolutionary Approach to Effort...,Danny Dreyer,"Paperback,– 5 May 2009",0.050347,-0.259449,The revised edition of the bestselling ChiRunn...,Healthy Living & Wellness (Books),Sports,900.00,71,-0.013062,71,1342,2,1
6,Death on the Nile (Poirot),Agatha Christie,"Paperback,– 5 Oct 2017",0.050347,0.501255,Agatha Christie’s most exotic murder mystery\n...,"Crime, Thriller & Mystery (Books)","Crime, Thriller & Mystery",224.00,26,0.025237,26,480,69,1
7,Yoga Your Home Practice Companion: A Complete ...,Sivananda Yoga Vedanta Centre,"Hardcover,– Import, 1 Mar 2018",0.050347,-0.164361,"Achieve a healthy body, mental alertness, and ...",Sports Training & Coaching (Books),Sports,836.00,169,-0.008275,169,691,2,1
8,Karmayogi: A Biography of E. Sreedharan,M S Ashokan,"Paperback,– 15 Dec 2015",0.050347,0.964810,Karmayogi is the dramatic and inspiring story ...,Biographies & Autobiographies (Books),"Biographies, Diaries & True Accounts",130.00,39,0.048575,39,864,1,1
9,"The Iron King (The Accursed Kings, Book 1)",Maurice Druon,"Paperback,– 26 Mar 2013",0.050347,-0.342651,‘This is the original game of thrones’ George ...,Action & Adventure (Books),Action & Adventure,695.00,42,-0.017251,42,926,3,-1
10,Battle for Sanskrit: Is Sanskrit Political or ...,Rajiv Malhotra,"Paperback,– 20 Jan 2017",0.050347,1.214416,There is a new awakening in India that is chal...,Asian History,"Language, Linguistics & Writing",373.00,94,0.061142,94,784,1,-1
11,Blockchain Revolution: How the Technology Behi...,"Don Tapscott, Alex Tapscott","Paperback,– Import, 14 Jun 2018",-1.269032,-0.152475,THE DEFINITIVE BOOK ON HOW THE TECHNOLOGY BEHI...,Banks & Banking,"Computing, Internet & Digital Media",309.00,105,0.193496,105,1472,1,1
12,Tai-Pan: The Second Novel of the Asian Saga,James Clavell,"Paperback,– 1 Jul 1999",0.050347,-0.306993,Set in the turbulent days of the founding of H...,Action & Adventure (Books),Action & Adventure,379.00,43,-0.015456,43,367,7,-1
13,The Art of Shaolin Kung Fu: The Secrets of Kun...,Wong Kiew Kit,"Paperback,– 15 Nov 2002",1.369725,-0.318879,The Art of Shaolin Kung Fu is the ultimate gui...,Asian History,Sports,1066.00,116,-0.436777,116,2577,1,-1
14,Anil's Ghost,Michael Ondaatje,"Paperback,– 1 Sep 2011",-1.269032,-0.295107,"Anil's Ghost transports us to Sri Lanka, a cou...",Action & Adventure (Books),Romance,381.22,12,0.374501,12,671,4,-1
15,Superman: An Origin Story (DC Comics Super Her...,Matthew K Manning,"Paperback,– 26 Feb 2015",1.369725,-0.330765,"One day, an alien orphan crash-lands on Earth ...",Comics & Mangas (Books),Comics & Mangas,287.00,50,-0.453058,50,367,1,1
16,My First Book of London,"Charlotte Guillain, Roland Dry","Hardcover,– 8 Mar 2018",1.369725,-0.342651,London is one of the most exciting cities in t...,Children's Mysteries & Curiosities (Books),"Crime, Thriller & Mystery",162.00,23,-0.469338,23,631,1,1
17,"Naruto: Itachi's Story, Vol. 1: Daylight",Takashi Yano,"Paperback,– 1 Nov 2016",0.050347,-0.081159,"A new series of prose novels, straight from th...",Mangas,Comics & Mangas,587.00,40,-0.004086,40,601,2,-1
18,The Story of Philosophy,Will Durant,"Mass Market Paperback,– 1 Jan 1991",0.050347,0.548799,A brilliant and concise account of the lives a...,Biographies & Autobiographies (Books),"Biographies, Diaries & True Accounts",291.00,23,0.027630,23,607,1,1
19,"Introducing Data Science: Big Data, Machine Le...","Davy Cielen, Arno D.B. Meysman, Mohamed Ali","Paperback,– 2016",0.050347,-0.295107,Introducing Data Science explains vital data s...,Artificial Intelligence,"Computing, Internet & Digital Media",352.00,82,-0.014858,82,568,1,1

In [27]:
author_target_mean = df.groupby('Author')['Price'].mean()
df['Author encoded'] = df['Author'].map(author_target_mean)
df.drop(columns=['Author'], inplace=True)

In [28]:
df.columns

Index(['Title', 'Edition', 'Reviews', 'Ratings', 'Synopsis', 'Genre',
       'BookCategory', 'Price', 'Title len', 'Rating Review score',
       'Title Char length', 'Synopsis len', 'Author freq', 'Synopsis Polarity',
       'Author encoded'],
      dtype='object')

In [ ]:
df.drop(["Title","BookCategory"], axis=1, inplace=True)

In [31]:
df["Genre Freq"] = df["Genre"].map(df["Genre"].value_counts())

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Limit max_features to avoid high dimensionality (adjust as needed)
tfidf = TfidfVectorizer(max_features=300, stop_words='english')

# Fit and transform the Synopsis column
tfidf_matrix = tfidf.fit_transform(df['Synopsis'].fillna(""))

# Convert to DataFrame and rename columns
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=[f"tfidf_syn_{word}" for word in tfidf.get_feature_names_out()])

# Concatenate with original dataframe
df = pd.concat([df.reset_index(drop=True), tfidf_df.reset_index(drop=True)], axis=1)

In [34]:
df.drop("Synopsis",axis=1,inplace=True)
# One-hot encode the 'Genre' column
genre_dummies = pd.get_dummies(df['Genre'], prefix='Genre',dtype=int)

# Concatenate the new one-hot columns with the original DataFrame
df = pd.concat([df.drop('Genre', axis=1), genre_dummies], axis=1)

In [36]:
df.drop("Edition",axis=1,inplace=True)

In [37]:
df

,Reviews,Ratings,Price,Title len,Rating Review score,Title Char length,Synopsis len,Author freq,Synopsis Polarity,Author encoded,...,Genre_Vocabulary Books,"Genre_Walking, Hiking & Trekking (Books)",Genre_Waste Management,"Genre_Words, Language & Grammar Reference",Genre_Workbooks,Genre_World African & Middle Eastern Literature,Genre_Writing Guides (Books),Genre_XHTML Software Programming,Genre_Young Adults' Money & Jobs (Books),Genre_Zoology
0,0.050347,-0.259449,220.00,35,-0.013062,35,791,4,1,227.00000,...,0,0,0,0,0,0,0,0,0,0
1,-1.269032,-0.188133,202.93,34,0.238747,34,1146,1,1,202.93000,...,0,0,0,0,0,0,0,0,0,0
2,0.050347,-0.283221,299.00,28,-0.014259,28,1662,3,1,299.00000,...,0,0,0,0,0,0,0,0,0,0
3,0.050347,-0.200019,180.00,34,-0.010070,34,426,69,-1,241.17087,...,0,0,0,0,0,0,0,0,0,0
4,1.369725,-0.342651,965.62,42,-0.469338,42,659,1,1,965.62000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6232,1.369725,-0.330765,322.00,50,-0.453058,50,1348,1,1,322.00000,...,0,0,0,0,0,0,0,0,0,0
6233,-1.269032,-0.247563,421.00,11,0.314166,11,1349,1,-1,421.00000,...,0,0,0,0,0,0,0,0,0,0
6234,-1.269032,-0.318879,399.00,54,0.404668,54,1285,3,1,449.00000,...,0,0,0,0,0,0,0,0,0,0
6235,-1.269032,-0.306993,319.00,28,0.389584,28,926,2,1,321.58000,...,0,0,0,0,0,0,0,0,0,0
6236,-1.269032,-0.330765,452.00,27,0.419752,27,790,2,-1,366.00000,...,0,0,0,0,0,0,0,0,0,0